strings = {
	generate_doc: "Сгенерировать"
,	success: "Добились своего"
,	failure: "Все наперекосяк"
,	hello: "Ave, "
,	first: "Первая"
,	second: "Вторая"
,	third: "Третья"
,	read: "Ознакомиться"
,	show: "Показать подробную информацию"
,	hide: "Скрыть"
, 	DateOfComplaining: "Дата подачи апелляции:"
,	DateOfResult: "Ответ должен быть получен до: "
,	gotoRusEdEx: "Войти в Электронную Приемную"
}
